menu:
  dashboard:
    name: dashboard
    url_path: /admin/dashboard
    icon: dashboard
    current: ["keppler_ga_dashboard/dashboard"]
  user:
    name: users
    url_path: /admin/users
    icon: account_circle
    current: ["users"]
  blog:
    name: blog
    icon: library_books
    current: ["blog"]
    submenu:
      - categories:
          name: categories
          url_path: 
          current: ["1", "2"]
      - posts:
          name: posts
          url_path:
          current: