menu:
  dashboard:
    name: dashboard
    url_path: /admin/dashboard
    icon: dashboard
    current: ["keppler_ga_dashboard/dashboard"]
  user:
    name: users
    url_path: /admin/users
    icon: account_circle
    current: ["users"]
    model: User
  google_analytics_track:
    name: google analytics tracks
    url_path: /admin/google_analytics_tracks
    icon: insert_chart
    current: ['google_analytics_tracks']
    model: GoogleAnalyticsTrack
  setting:
    name: setting
    current: ["settings"]
    icon: settings
    model: Setting
    submenu:
      - basic_information:
          name: Basic information
          url_path: /admin/settings/basic_information
          current: ["basic_information"]
      - smtp_setting:
          name: Emial setting (SMTP)
          url_path: /admin/settings/email_setting
          current: ["email_setting"]
      - google_analytics_setting:
          name: Google analytics
          url_path: /admin/settings/google_analytics_setting
          current: ["google_analytics_setting"]
